task-2
massimoteplovsky/junior-course-boilerplate pull request #4
Opened 2021-02-25 16:29 UTC by massimoteplovsky

2021-02-28 11:30 UTC, vislogurov requested changes

2021-02-28 11:30 UTC, vislogurov commented on src/components/ProductsList/ProductsList.jsx
> +        products.map((product) => (
Нужно предусмотреть какой-то UI на случай, если массив produсts пустой или вовсе не пришел. Например "Список товаров пуст"

2021-02-28 11:30 UTC, vislogurov commented on src/components/Title/Title.jsx
> +    <h1 className={s.title}>{text}</h1>
В целом такое решение тоже имеет место быть. Но, хорошей практикой в этом случае, будет использование пропса children. Такой поход позволяет более универсально передавать контент в компоненты:

```
<Title>
 // любой контент
</Title>
```
Дополнительно, такой подход открывает возможности для использования Children API https://reactjs.org/docs/react-api.html#reactchildren , когда нам нужно _что то _ сделать с чилдренами дополнительно

2021-02-28 11:30 UTC, vislogurov commented on src/components/ProductItem/ProductItem.jsx
> +        alt="placeholder"
Не просто "placeholder", а описание изображения. Скринридеры будут использовать alt в качестве альтернативы, для описания страницы.

2021-02-28 11:30 UTC, vislogurov commented on src/components/ProductsList/ProductsList.jsx
> +    <div className={s.productsList}>
Если это list, то почему это `div`?)

2021-02-28 11:30 UTC, vislogurov commented on src/components/App/App.jsx
> +    <div className="container">
Отличное место для тэга `main`

2021-03-01 13:20 UTC, massimoteplovsky commented on src/components/ProductsList/ProductsList.jsx
> +    <div className={s.productsList}>
Смутило div внутри li

2021-03-01 14:14 UTC, vislogurov approved these changes

2021-03-01 14:26 UTC, merged