task-3
massimoteplovsky/junior-course-boilerplate pull request #5
Opened 2021-03-02 13:50 UTC by massimoteplovsky

2021-03-02 14:07 UTC, vislogurov requested changes

2021-03-02 14:07 UTC, vislogurov commented on src/components/App/App.jsx
> +    const newProducts = [...products];
`newProducts.filter()` и так вернёт новый массив, кажется копия `...products` излишняя

2021-03-02 14:07 UTC, vislogurov commented on src/components/ProductItem/ProductItem.jsx
> +    const {title,
Что то с переносами

2021-03-02 14:07 UTC, vislogurov commented on src/components/ProductItem/ProductItem.jsx
> +          isInStock} = this.props;
Тут тоже

2021-03-02 14:07 UTC, vislogurov commented on src/components/ProductFilterForm/ProductFilterForm.jsx
> +  changePriceRangeHandler = (e) => this.props.onChangePriceRange(e.target);
В целом решение подходящее. А могли бы мы тут обойтись рефами? Есть понимание какой недостаток/профит от подхода с рефами?

2021-03-02 17:01 UTC, massimoteplovsky commented on src/components/ProductFilterForm/ProductFilterForm.jsx
> +  changePriceRangeHandler = (e) => this.props.onChangePriceRange(e.target);
Да, можно было бы установить рефы на инпуты и дефолтное значение. Далее в changePriceRangeHandler также приходили бы данные инпута. Придется переписать? Из недостатков рефов - нет полного контроля над элементами формы. В основном, рефы используются для фокусирвоки инпутов, анимаций, интеграции со сторонними библиотеками.

2021-03-03 13:14 UTC, vislogurov commented on src/components/ProductFilterForm/ProductFilterForm.jsx
> +  changePriceRangeHandler = (e) => this.props.onChangePriceRange(e.target);
Переписывать не нужно. Такой тип контроля инпутов это как раз следующая тема, нужно было выяснить насколько глубоко тебе понятна разница)))

2021-03-03 13:16 UTC, vislogurov commented on src/components/App/App.jsx
> +    const newProducts = [...products];
Ставь плз плюсик или галочку или "done", если пофиксил коммент. Иначе ревьюеру непонятно: то ли коммент поправлен, то ли вызывает вопрос, то ли про него забыли.

2021-03-03 13:16 UTC, vislogurov approved these changes

2021-03-03 14:52 UTC, merged