task-5
massimoteplovsky/junior-course-boilerplate pull request #7
Opened 2021-03-13 16:47 UTC by massimoteplovsky

Реализовал кривоватенькую динамическую пагинацию. Можно ли использовать плагин или только своими силами все?)

2021-03-15 15:39 UTC, vislogurov commented
Лучше самому, тогда понятное будет от чего строятся решения в уже готовых библиотеках. Это знание позволит переписать её под свои нужды)))

2021-03-15 15:49 UTC, vislogurov requested changes

2021-03-15 15:49 UTC, vislogurov commented on src/components/App/App.jsx
> +          ...categories.slice(0, itemIndex),
Уже в третий раз спотыкаемся) slice и так вернёт новый массив, `... categories ` лишнюю память только займёт

2021-03-15 15:49 UTC, vislogurov commented on src/components/Checkbox/Checkbox.jsx
> +        onClick={() => onChangeFilterCategories(category)}
Обрати внимание, что функция анонимная, следовательно каждый раз она будет создавать новая, что вызовет "холостой" рендер. Это _может_ привести в будущем в проблемам производительности.

Прямо сейчас это мало на что повлияет, но иметь ввиду нужно.

https://ru.reactjs.org/docs/faq-functions.html

2021-03-15 15:49 UTC, vislogurov commented on src/components/Pagination/Pagination.jsx
> +  // render() {
Если комментишь что-то, то оставляй TODO-коммент: "Закомментил потому что тратата, исправится когда случится то то и то". Либо удаляй совсем.

2021-03-15 15:49 UTC, vislogurov commented on src/components/Pagination/Pagination.jsx
> +  generatePages = (page, totalPages) => {
в целом, если какие то куски рендера выносятся в отдельные методы, то это сигнал к созданию нового компонента. Иначе потом придётся копипастить этот кусок, когда пагинация нужна будет где-то ещё.

2021-03-15 15:49 UTC, vislogurov commented on src/index.css
> +/* .pagination {
Тут такое же замечание про комменты

2021-03-15 16:08 UTC, massimoteplovsky commented on src/components/App/App.jsx
> +          ...categories.slice(0, itemIndex),
Ясно, понятно)

2021-03-15 16:09 UTC, massimoteplovsky commented on src/components/Checkbox/Checkbox.jsx
> +        onClick={() => onChangeFilterCategories(category)}
Я помню, что это опасно при ее передаче во вложенный компонент.

2021-03-16 11:47 UTC, vislogurov approved these changes

2021-03-16 12:18 UTC, merged