task-7
massimoteplovsky/junior-course-boilerplate pull request #9
Opened 2021-03-22 16:51 UTC by massimoteplovsky

Не совсем понятно было как именно организовать добавление параметров в query string...(

2021-03-23 10:39 UTC, vislogurov commented
А вопрос актуальный ещё? Я пока по коду не вижу, чтобы сложности возникли. Давай попробуем локализовать проблему.

2021-03-24 08:03 UTC, vislogurov requested changes

2021-03-24 08:03 UTC, vislogurov commented on src/hocs/withHistory.js
> +      console.log(this.props);
Не оставляй логи в коде, они же потом на "бой" пападут

2021-03-24 08:03 UTC, vislogurov commented on src/hocs/withHistory.js
> +      // const searchParams = new URLSearchParams(this.props.query);
Либо пиши зачем закомментил, либо удаляй коммент совсем.

2021-03-24 08:03 UTC, vislogurov commented on src/state/modules/pagination.js
> +import {createAction, createReducer} from '@reduxjs/toolkit';
Хорошо бы обосновать, почему тут не хватило стандартных редюсеров и action-криэйторов

2021-03-24 08:03 UTC, vislogurov commented on src/components/Pagination/Pagination.jsx
> +  const renderFirstButtons = () => {
renderFirst/Middle/Last buttons — по сути функции одной структуры, тут прямо таки напрашивается компонент, реализующий "фабрику рендер функций"

2021-03-24 08:03 UTC, vislogurov commented on src/components/Pagination/Pagination.jsx
>        return generateCustomArray(totalPages, 1);
Нужно определиться, что ты генеришь pages или customArray? Если с pages всё понятно, то как не заглядывая в функцию определить, что такое customArray?

2021-03-24 08:03 UTC, vislogurov commented on src/components/Pagination/Pagination.jsx
> +            <span className={cx(s.btn, s.btnPage)}>...</span>
Если это btn, то почему это span?

2021-03-24 08:03 UTC, vislogurov commented on src/components/Pagination/Pagination.jsx
> +const MIN_PAGES_COUNT = 5;
Почему эти ограничения не вынесены на уровень стора или контейнера? Получается что "тупой" компонент уже что то знает о структуре страниц.

2021-03-24 13:56 UTC, massimoteplovsky commented on src/state/modules/pagination.js
> +import {createAction, createReducer} from '@reduxjs/toolkit';
Решил использовать Redux Toolkit для меньшего boilerpale type, actions etc...

2021-03-25 13:09 UTC, vislogurov approved these changes

2021-03-25 13:09 UTC, vislogurov commented on src/components/PaginationBtn/PaginationBtn.jsx
> +const PaginationBtn = ({
Название компонента крайне неудачное — читающий увидит импорт PagintaionBtn, и будет думать, что это лишь компонент кнопки, хотя по сути это целый "кнопочный комбаин"

2021-03-25 13:26 UTC, merged